name: OriginatedClasses
version: ${project.version}
api-version: 1.16
author: Jacrispys
main: com.Jacrispys.OriginatedClasses.OriginatedClassesMain
softdepend: [LuckPerms]
commands:
  origins:
  roam:
