name: OriginatedClasses
version: ${project.version}
api-version: 1.16
author: Jacrispys
main: com.Jacrispys.OriginatedClasses.OriginatedClassesMain
softdepend: [LuckPerms]
depend: [ProtocolLib]
commands:
  bear:
    aliases: []

  origins:
    aliases: []

  roam:
    aliases: []

  openreward:
    aliases: []

  loop:
    aliases: []

  lag:
    aliases: []



